

  luclean <- tibble::tribble(~clean, ~desc,
                             "all", "starting point",
                             "temp_range", "within a date (temporal) range",
                             "temp_bin", "assigning dates to temporal bins",
                             "temp_rel", "temporal reliability",
                             "geo_range", "within a geographic area",
                             "geo_bin", "assigning locations to spatial bins",
                             "geo_rel", "spatial reliability",
                             "context", "define context",
                             "att", "add non-spatial attributes",
                             "geo", "add geographic context (e.g. IBRA)",
                             "ann", "non-persistent taxa",
                             "taxa", "align taxonomy and resolve any taxonomic duplication within bins",
                             "single", "singletons",
                             "out", "outliers",
                             "NA", "NA values in important columns",
                             "ll", "NA values in latitude/longitude columns",
                             "effort", "context effort",
                             "prop","proportion of sites",
                             "life", "as a byproduct of assigning all records of a taxa a lifeform",
                             "cov", "as a byproduct of assigning all records of a taxa a cover value",
                             "recent", "the most recent visit to a cell",
                             "lists", "add list length",
                             "filt_list_df", "filter occurrence data to a set of criteria",
                             "fst", "fix spatial taxonomy",
                             "fbd", "filter by distribution",
                             "pres", "presences only",
                             "coord", "centroids of state, capital and institutions",
                             "ind", "indigenous species",
                             "rm", "geographic reliability",
                             "include", "taxa with presences, reliable distributions, and/or mcp around presences",
                             "bin", "add temporal, geographic and/or taxonomic bins",
                             "region_taxa", "taxa found within a geograpic area (but including their records outside that area)",
                             "spt_att", "add spatially dependent attributes",
                             "fr", "fix reliability",
                             "clean", "final step in the generic cleaning process",
                             "tax_level", "all records identified to at least a specific taxonomic level",
                             "novagrant", "filter vagrant records",
                             "noextinct", "filter records from an extinct part of a taxas range",
                             "nohaven", "filter records from inside havens",
                             "tg", "was the list long enough to imply good survey effort (and therefore absence may be implied for taxa not recorded here)"
                             ) %>%
    dplyr::mutate(order = dplyr::row_number() - 1) %>%
    dplyr::arrange(order)
