### Spatial reliability

Any record with a spatial reliability greater than `r use_rel_dist` metres was removed, using the function `filter_spat_rel` from the package `envClean` `r cite_package("envClean")`.

Some data sources did not provide a spatial reliability. These data sources (`r include_data_name[include_data_name %in% unique(bio_all$data_name)]`) were allowed through this filtering step. Some surveys were also allowed through this filtering step where they were known to be recent and undertaken by skilled observers. If allowed through in this manner, any record with a spatial reliability greater than `r use_extra_rel_dist` metres was removed.

In preparing for the analysis of South Australian ecosystems, spatial areas that lost many records through the spatial reliability filtering were identified. In these areas records were manually relocated by one of us (KR) to a location as close to the original as possible that conceptually aligned:

* aerial imagery
* plant species list
* relevant satellite data
* and, in some cases, the original mud-map from the survey

These relocated records had their [BDBSA](#bdbsa) location and spatial reliability adjusted so that they passed the spatial reliability filtering.

`r data_filter$filter_text[i]`

<br>
