# Filter by distribution: `bio_fbd` {#fbd}

Erroneous or vagrant records were filtered by comparing records to known distributions for taxa where distributions were available, using the `filter_by_distribution` function. These distributions (created in the **envVec** project) were sourced from:

-  [Environment Protection and Biodiversity Conservation (EPBC) Act listings](https://fed.dcceew.gov.au/datasets/d0107a2f33a64ef4b9ffd7195dfb1b89/about)
-  the Expert distributions layer for some South Australian taxa in EGIS (internal DEW dataset)
-  [Birds SA vetted distributions](https://birdssa.asn.au/distribution-maps/)
-  IUCN Red List maps - directly from the [IUCN Red List](https://www.iucnredlist.org/resources/spatial-data-download) for non-avian taxa; and [BirdLife International](https://datazone.birdlife.org/species/requestdis) for avian taxa.
-  [Flora of South Australia](https://flora.sa.gov.au/)
-  [SA Seed Conservation Centre](https://www.botanicgardens.sa.gov.au/science/conservation/south-australian-seed-conservation-centre) at the State Herbarium

For cases where taxa had a distribution in more than one source, distribution sources were ranked such that the most authoritative or fine-scaled were used over broader or less authoritative sources (e.g. EPBC \> Birds SA \> Expert \> Red List). Records were filtered if they were \> `r clean_settings$fbd_dist` km from the relevant known distribution to allow for uncertainty. This buffer was not used for EPBC distributions, as these already included included a 'may occur' category that covered areas around known ranges and serves the same purpose.
